version: 0.2

env:
  variables:
    CLUSTER_NAME: "java-ci-cd-cluster"
    REGION: "us-east-1"
    REPO_NAME: "java-ci-cd-app"

phases:
  pre_build:
    commands:
      - echo "Resolving account and registry..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
      - ECR_REPO="${REGISTRY}/${REPO_NAME}"
      - echo "Logging in to ECR registry ${REGISTRY}..."
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${REGISTRY}
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c1-7)
      - echo "Using image: ${ECR_REPO}:${IMAGE_TAG}"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO}:${IMAGE_TAG} .
      - echo "Pushing image to ECR..."
      - docker push ${ECR_REPO}:${IMAGE_TAG}
  post_build:
    commands:
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig --region ${REGION} --name ${CLUSTER_NAME}
      - echo "Deploying with Helm..."
      - helm upgrade --install java-ci-cd-app ./helm \
          --set image.repository=${ECR_REPO} \
          --set image.tag=${IMAGE_TAG}
