version: 0.2

env:
  variables:
    ECR_REPO: "<your-account-id>.dkr.ecr.us-east-1.amazonaws.com/java-ci-cd-app"
    CLUSTER_NAME: "java-ci-cd-cluster"
    REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --region $REGION ecr get-login-password | docker login --username AWS --password-stdin $ECR_REPO
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - echo Pushing Docker image...
      - docker push $ECR_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
      - echo Deploying with Helm...
      - helm upgrade --install java-ci-cd-app ./helm --set image.repository=$ECR_REPO --set image.tag=$IMAGE_TAG
